/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Student/change-password/[studentId]': RouteRecordInfo<'/Student/change-password/[studentId]', '/Student/change-password/:studentId', { studentId: ParamValue<true> }, { studentId: ParamValue<false> }>,
    '/Student/dashboard': RouteRecordInfo<'/Student/dashboard', '/Student/dashboard', Record<never, never>, Record<never, never>>,
    '/Student/login': RouteRecordInfo<'/Student/login', '/Student/login', Record<never, never>, Record<never, never>>,
  }
}
